# Generated by Django 3.2.4 on 2022-03-02 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('identitynum', models.CharField(max_length=9)),
                ('medicalpass', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('contactnum', models.IntegerField(validators=[django.core.validators.MinValueValidator(60000000), django.core.validators.MaxValueValidator(99999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('identitynum', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('contactnum', models.IntegerField(validators=[django.core.validators.MinValueValidator(60000000), django.core.validators.MaxValueValidator(99999999)])),
                ('allergies', models.CharField(max_length=500)),
                ('medhistory', models.CharField(max_length=500)),
            ],
        ),
    ]
